#!/bin/fish
argparse h/help -- $argv
or return
set usage "Usage: gnome_conf [-h | --help] backup|restore"
# Checking for _flag_h and _flag_help is equivalent
# We check if it has been given at least once
if set -ql _flag_h
    echo "$usage" >&2
    return 1
end
set temp_dir $(mktemp -d gnome_ext_XXX)
for arg in $argv
    echo " ->> Extension : $arg"
    set version_tag $(curl -Lfs "https://extensions.gnome.org/extension-query/?search=$arg" | jq '.extensions[0] | .shell_version_map | map(.pk) | max')
    if wget -q -O "$temp_dir/$arg.zip" "https://extensions.gnome.org/download-extension/$arg.shell-extension.zip?version_tag=$version_tag"
        echo "     - Downloaded : $arg.zip"
    else
        echo "     - Could not download : $arg.zip"
    end
end
tree -f $temp_dir
rm -rf $temp_dir
