#!/bin/fish
argparse h/help -- $argv
or return
set usage "Usage: gnome_conf [-h | --help] backup|restore"
# Checking for _flag_h and _flag_help is equivalent
# We check if it has been given at least once
if set -ql _flag_h
    echo "$usage" >&2
    return 1
end
for arg in $argv
    switch $arg
        case backup
            echo backup gnome settings
            dconf dump /org/gnome/shell/extensions/ >~/dotfiles/gnome/org_gnome_shell_extensions.ini
            dconf dump /org/gnome/desktop/wm/keybindings/ >~/dotfiles/gnome/org_gnome_desktop_wm_keybindings.ini
        case restore
            echo restore
            dconf load /org/gnome/shell/extensions/ <~/dotfiles/gnome/org_gnome_shell_extensions.ini
            dconf load /org/gnome/desktop/wm/keybindings/ <~/dotfiles/gnome/org_gnome_desktop_wm_keybindings.ini
        case '*'
            echo "$usage"
    end
end
